### PR TITLE
Add support for GNOME 44

### LINKED ISSUE #218: Add support for GNOME 44
https://release.gnome.org/44/

https://fedoramagazine.org/announcing-fedora-38/

### PR DESCRIPTION
**Pull request by gtirloni**
Fixes #218

Tested on Fedora 38 with GNOME 44.

### CODE REVIEW

**Comment by konkor** [comment]
Thanks

**Comment by luisalvarado** [comment]
Jesus, Konkor, you are too fast!! Okay will wait to test it on the gnome extensions page, but basically I can NOT complain at all.

**Comment by TuxyKey** [comment]
does this mean we will soon see this on the gnome extension page ? thanks for all your great work @konkor and of course @gtirloni ..

**Comment by BloodyIron** [comment]
Just upgraded to Ubuntu 23.04 and I can't use this lovely extension (which I use every single day) until this update hits main repos :( What kind of a timeline is anticipated for this? :)

Thanks for the work on this! This tool has provided significant value to me (keeping system cool while general use, then fastttt when I really need it).

**Comment by konkor** [comment]
Done. it's available on the extensions page

**Comment by BloodyIron** [comment]
> Done. it's available on the extensions page

Yay! Thanks! :D

**Comment by TuxyKey** [comment]
Thank you so much @konkor .. Coffee on me via paypal.. Greetings from the Netherlands.

**Pull request merged**
