### PR TITLE
Support Gnome Shell 43

### PR DESCRIPTION
**Pull request by bjhulst**
Support Gnome Shell 43

### CODE REVIEW

**Comment by bjhulst** [comment]
Related to issue https://github.com/konkor/cpufreq/issues/210

**Comment by dpellegr** [comment]
Could you please merge this, so that hopefully it will be installable from https://extensions.gnome.org/

**Comment by konkor** [comment]
thank you, nice job!

**Comment by pipes80-collab** [comment]
nice to read you @konkor

**Pull request merged**
